"""A library for extracting type annotations as a graph."""

from importlib.metadata import version

from typing_inspection.introspection import Qualifier

from ._config import EvalMode, InspectConfig
from ._inspect_class import (
    ClassInspectResult,
    inspect_class,
    inspect_dataclass,
    inspect_enum,
    inspect_named_tuple,
    inspect_protocol,
    inspect_typed_dict,
)
from ._inspect_function import inspect_function, inspect_signature
from ._inspect_module import ModuleTypes, inspect_module
from ._inspect_type import (
    clear_cache,
    get_type_hints_for_node,
    inspect_type,
    inspect_type_alias,
)
from ._node import (
    AnnotatedType,
    AnyType,
    AttrsFieldDef,
    AttrsType,
    CallableType,
    ClassNode,
    ConcatenateNode,
    ConcreteType,
    DataclassFieldDef,
    DataclassType,
    EllipsisType,
    EnumType,
    FieldDef,
    ForwardRef,
    FunctionNode,
    GenericAlias,
    GenericTypeNode,
    LiteralNode,
    MetaType,
    MethodSig,
    NamedTupleType,
    NeverType,
    NewTypeNode,
    Parameter,
    ParamSpecNode,
    ProtocolType,
    PydanticFieldDef,
    PydanticModelType,
    RefState,
    SelfType,
    SignatureNode,
    SourceLocation,
    SubscriptedGeneric,
    TupleType,
    TypeAliasNode,
    TypedDictType,
    TypeGuardType,
    TypeIsType,
    TypeNode,
    TypeVarNode,
    TypeVarTupleNode,
    UnionType,
    UnpackNode,
    Variance,
)

__all__ = [
    "AnnotatedType",
    "AnyType",
    "AttrsFieldDef",
    "AttrsType",
    "CallableType",
    "ClassInspectResult",
    "ClassNode",
    "ConcatenateNode",
    "ConcreteType",
    "DataclassFieldDef",
    "DataclassType",
    "EllipsisType",
    "EnumType",
    "EvalMode",
    "FieldDef",
    "ForwardRef",
    "FunctionNode",
    "GenericAlias",
    "GenericTypeNode",
    "InspectConfig",
    "LiteralNode",
    "MetaType",
    "MethodSig",
    "ModuleTypes",
    "NamedTupleType",
    "NeverType",
    "NewTypeNode",
    "ParamSpecNode",
    "Parameter",
    "ProtocolType",
    "PydanticFieldDef",
    "PydanticModelType",
    "Qualifier",
    "RefState",
    "SelfType",
    "SignatureNode",
    "SourceLocation",
    "SubscriptedGeneric",
    "TupleType",
    "TypeAliasNode",
    "TypeGuardType",
    "TypeIsType",
    "TypeNode",
    "TypeVarNode",
    "TypeVarTupleNode",
    "TypedDictType",
    "UnionType",
    "UnpackNode",
    "Variance",
    "__version__",
    "clear_cache",
    "get_type_hints_for_node",
    "inspect_class",
    "inspect_dataclass",
    "inspect_enum",
    "inspect_function",
    "inspect_module",
    "inspect_named_tuple",
    "inspect_protocol",
    "inspect_signature",
    "inspect_type",
    "inspect_type_alias",
    "inspect_typed_dict",
]

__version__ = version("typing-graph")
